apiVersion: v1
kind: Pod
metadata:
  namespace: production
  name: simple-webapp-color-blue
  labels:
    app: web
spec:
  containers:
    - name: simple-webapp-color-blue
      image: mmumshad/simple-webapp-color:latest
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: blue 

